services:
  - type: web
    name: louvre-api-server
    env: node
    buildCommand: |
      npm install
      npm install --save-dev @types/node@18.18.0
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health 