name: Deploy Louvre API Server

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/

  deploy-to-github-releases:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: dist/
    
    - name: Create release archive
      run: |
        # Create a zip file of the build
        zip -r louvre-api-server.zip dist package.json README.md
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: louvre-api-server.zip
        name: Release ${{ github.sha }}
        tag_name: v${{ github.run_number }}
        body: |
          Louvre API Server Release
          
          Commit: ${{ github.sha }}
          Workflow: ${{ github.workflow }}
          Run: ${{ github.run_number }}
          
          This release was automatically generated by GitHub Actions.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Optional: Only run this job if you want to publish to npm
  deploy-to-github-packages:
    needs: build
    runs-on: ubuntu-latest
    if: false # Disable this job by default
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: dist/
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@${{ github.repository_owner }}'
    
    - name: Install dependencies
      run: npm install
    
    - name: Prepare package for GitHub Packages
      run: |
        # Create or update .npmrc file for GitHub Packages
        echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com" > .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
        
        # Check if jq is available, install if not
        if ! command -v jq &> /dev/null; then
          echo "jq not found, installing..."
          sudo apt-get update
          sudo apt-get install -y jq
        fi
        
        # Update package.json for GitHub Packages
        jq '.name = "@${{ github.repository_owner }}/louvre-api-server" | .publishConfig.registry = "https://npm.pkg.github.com" | .private = false' package.json > package.json.tmp
        mv package.json.tmp package.json
        
        # Bump version
        npm version patch --no-git-tag-version
    
    - name: Publish to GitHub Packages
      run: npm publish --registry=https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 