name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Create API documentation
        run: |
          mkdir -p docs
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Louvre API Server Documentation</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
            <style>
              body { padding-top: 2rem; }
              .endpoint { margin-bottom: 2rem; padding: 1rem; border-radius: 5px; background-color: #f8f9fa; }
              .method { font-weight: bold; color: #0d6efd; }
              pre { background-color: #f1f1f1; padding: 1rem; border-radius: 5px; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>Louvre API Server Documentation</h1>
              <p class="lead">A Node.js API server that provides access to artwork data from the Louvre Museum collection.</p>
              
              <h2 class="mt-4">API Endpoints</h2>
              
              <div class="endpoint">
                <h3><span class="method">GET</span> /api/search_artwork</h3>
                <p>Search for artwork in the Louvre collection.</p>
                <h4>Query Parameters:</h4>
                <ul>
                  <li><code>query</code> (required): Search term</li>
                  <li><code>page</code> (optional): Page number for pagination (default: 1)</li>
                </ul>
              </div>
              
              <div class="endpoint">
                <h3><span class="method">GET</span> /api/get_artwork_details/:id</h3>
                <p>Get detailed information about a specific artwork.</p>
                <h4>Path Parameters:</h4>
                <ul>
                  <li><code>id</code> (required): Artwork ID</li>
                </ul>
              </div>
              
              <div class="endpoint">
                <h3><span class="method">GET</span> /api/get_artwork_image/:id</h3>
                <p>Get images for an artwork organized by type.</p>
                <h4>Path Parameters:</h4>
                <ul>
                  <li><code>id</code> (required): Artwork ID</li>
                </ul>
                <h4>Query Parameters:</h4>
                <ul>
                  <li><code>type</code> (optional): Image type to filter by</li>
                  <li><code>position</code> (optional): Specific image position to retrieve</li>
                </ul>
              </div>
              
              <div class="endpoint">
                <h3><span class="method">GET</span> /api/get_artist_timeline</h3>
                <p>Get a chronological timeline of an artist works.</p>
                <h4>Query Parameters:</h4>
                <ul>
                  <li><code>artist</code> (required): Artist name</li>
                  <li><code>sortBy</code> (optional): Sort method (date or popularity, default: date)</li>
                </ul>
              </div>
              
              <footer class="mt-5 pt-3 border-top text-muted">
                <p>Louvre API Server - <a href="https://github.com/${{ github.repository }}">GitHub Repository</a></p>
              </footer>
            </div>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
          </body>
          </html>' > docs/index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 